<?php
if (!isset($NEPA_LANGS)) {
    $NEPA_LANGS = [
        'en' => [
            'Home' => 'Home',
            'About Us' => 'About Us',
            'Contact Us' => 'Contact Us',
            'Login / Signup' => 'Login / Signup',
            'NepaCare' => 'NepaCare',
            'Welcome Back' => 'Welcome Back',
            'Please fill in all fields.' => 'Please fill in all fields.',
            'Enter a valid email or phone number starting with 97 or 98.' => 'Enter a valid email or phone number starting with 97 or 98.',
            'Incorrect password.' => 'Incorrect password.',
            'User not found.' => 'User not found.',
            'Email or Phone' => 'Email or Phone',
            'Password' => 'Password',
            'Remember me' => 'Remember me',
            'Login' => 'Login',
            "Don't have an account?" => "Don't have an account?",
            'Sign up' => 'Sign up',
            'All rights reserved.' => 'All rights reserved.',

            'Signup - NepaCare' => 'Signup - NepaCare',
            'Invalid phone number. Must start with 97 or 98 and be 10 digits.' => 'Invalid phone number. Must start with 97 or 98 and be 10 digits.',
            'Name can only contain letters and spaces.' => 'Name can only contain letters and spaces.',
            'Invalid email format.' => 'Invalid email format.',
            'Email or phone already registered. Please login.' => 'Email or phone already registered. Please login.',
            "Signup successful! You can <a href='login.php'>login now</a>." => "Signup successful! You can <a href='login.php'>login now</a>.",
            'Full Name' => 'Full Name',
            'Phone (97 or 98...)' => 'Phone (97 or 98...)',
            'Address' => 'Address',
            'Age' => 'Age',
            'Invalid age.' => 'Invalid age.',
            'Select Role' => 'Select Role',
            'Elder' => 'Elder',
            'Caregiver' => 'Caregiver',
            'Already have an account?' => 'Already have an account?',
            'Login here' => 'Login here'
            ,
            'Welcome to NepaCare' => 'Welcome to NepaCare',
            'For Elders' => 'For Elders',
            'For Caregivers' => 'For Caregivers',
            'Manage your daily reminders, medicines, and tasks easily. Stay healthy and organized with NepaCare.' => 'Manage your daily reminders, medicines, and tasks easily. Stay healthy and organized with NepaCare.',
            'Monitor elders’ reminders, support their health routines, and make caregiving easier.' => 'Monitor elders’ reminders, support their health routines, and make caregiving easier.'
            ,
            'About paragraph' => 'NepaCare is a platform dedicated to helping elders in Nepal manage daily tasks and medicines, ensuring safety and health. Caregivers can also monitor reminders and support elders efficiently. Our goal is to simplify elder care for families and professionals.',
            'Feedback' => 'Feedback',
            'Submit Feedback' => 'Submit Feedback',
            'Your feedback has been submitted.' => 'Your feedback has been submitted.',
            'Contact NepaCare' => 'Contact NepaCare',
            'Contact paragraph' => 'For any inquiries, feedback, or support, please contact us: <br><br> <strong>Email:</strong> nepacare2082@gmail.com <br> <strong>Phone:</strong> +977-9841077161 <br> <strong>Address:</strong> Kathmandu, Nepal',
            'Help Tip 1' => 'Tip: Remember to take your medicines on time to stay healthy.',
            'Help Tip 2' => 'Tip: Set reminders for important tasks to never forget.',
            'Help Tip 3' => 'Tip: Share your daily activities with your caregiver for better support.',
            'Assigned Elders' => 'Assigned Elders',
            'Tasks' => 'Tasks',
            'Linked Caregiver' => 'Linked Caregiver',
            'Health Tip 1' => 'Tip: Drink plenty of water daily to stay hydrated.',
            'Health Tip 2' => 'Tip: Eat a balanced diet with fruits and vegetables.',
            'Health Tip 3' => 'Tip: Get at least 7-8 hours of sleep every night.',
            'Health Tip 4' => 'Tip: Take short walks to improve circulation and mood.',
            'Subject' => 'Subject',
            'Message' => 'Message',
            'Send Feedback' => 'Send Feedback',
            'Please enter a message.' => 'Please enter a message.',
            'Caregiver Dashboard' => 'Caregiver Dashboard',
            'Elders Under Your Care' => 'Elders Under Your Care',
            'Add New Elder' => 'Add New Elder',
            'View Reminders' => 'View Reminders',
            'No elders found.' => 'No elders found.',
            'Elder Dashboard' => 'Elder Dashboard',
            'Your Reminders' => 'Your Reminders',
            'Add New Reminder' => 'Add New Reminder',
            'Mark as Done' => 'Mark as Done',
            'No reminders found.' => 'No reminders found.',
            'Update Profile' => 'Update Profile',
            'Profile updated successfully!' => 'Profile updated successfully!',
            'Add Reminder' => 'Add Reminder',
            'Get in Touch' => 'Get in Touch',
            'Send Message' => 'Send Message',
            'Thank you for your message!' => 'Thank you for your message!',
            'Manage Users' => 'Manage Users',
            'User List' => 'User List',
            'Approve' => 'Approve',
            'Reject' => 'Reject',
            'No users found.' => 'No users found.',
            'Manage Registrations' => 'Manage Registrations',
            'Registration List' => 'Registration List',
            'No registrations found.' => 'No registrations found.',
            'Admin Dashboard' => 'Admin Dashboard',
            'Welcome to Admin Panel' => 'Welcome to Admin Panel',
            'Caregiver Profile' => 'Caregiver Profile',
            'Caregiver Reminders' => 'Caregiver Reminders',
            'Reminders for Elder' => 'Reminders for Elder',
            'Elder Linked' => 'Elder Linked',
            'You are linked to Caregiver' => 'You are linked to Caregiver',
            'Caregiver Name' => 'Caregiver Name',
            'Caregiver Phone' => 'Caregiver Phone',
            'Caregiver Email' => 'Caregiver Email',
            'Generate OTP' => 'Generate OTP',
            'Enter your phone number' => 'Enter your phone number',
            'OTP sent successfully!' => 'OTP sent successfully!',
            'Are you sure?' => 'Are you sure?',
            'Welcome, ' => 'Welcome, ',
            'Linked Elder: ' => 'Linked Elder: ',
            'No login records found.' => 'No login records found.',
            'Caregiver about paragraph' => 'NepaCare is a simple reminder and care-support system designed especially for elders in Nepal. As a caregiver, you can help elders by managing their reminders, checking schedules, and supporting daily tasks.',
            'Reminders' => 'Reminders',
            'Link Elder' => 'Link Elder',
            'Logout' => 'Logout',
            'Good morning' => 'Good morning',
            'Good afternoon' => 'Good afternoon',
            'Good evening' => 'Good evening',
            'Daily Activity Reminder' => 'Daily Activity Reminder',
            'Morning Walk' => 'Morning Walk',
            'Drink Water' => 'Drink Water',
            'Exercise Time' => 'Exercise Time',
            'Health Tip' => 'Health Tip',
            'Wellness Check' => 'Wellness Check',
            'How are you feeling today?' => 'How are you feeling today?',
            'Good' => 'Good',
            'Okay' => 'Okay',
            'Not well' => 'Not well',
            'Elder about paragraph' => 'NepaCare is a simple, easy-to-use reminder system designed especially for elders. You can manage your daily tasks, set reminders, and receive alerts when it\'s time to do something important. This system ensures you never miss a task and helps caregivers stay informed.',
            'Keep up the great work! Stay active today.' => 'Keep up the great work! Stay active today.',
            'Take some rest and do light activity if possible.' => 'Take some rest and do light activity if possible.',
            'Please consult your caregiver or doctor if needed.' => 'Please consult your caregiver or doctor if needed.',
            'Profile' => 'Profile',
            'Name' => 'Name',
            'Email' => 'Email',
            'Phone' => 'Phone',
            'Address' => 'Address',
            'Age' => 'Age',
            'Change Password (leave blank to keep current)' => 'Change Password (leave blank to keep current)',
            'Role:' => 'Role:',
            'Current Time:' => 'Current Time:',
            'Failed to update profile.' => 'Failed to update profile.',
            'Email or phone already in use by another user.' => 'Email or phone already in use by another user.',
            'Name, email, and phone cannot be empty.' => 'Name, email, and phone cannot be empty.'
        ],
        'ne' => [
            'Home' => 'गृहपृष्ठ',
            'About Us' => 'हाम्रो बारेमा',
            'Contact Us' => 'सम्पर्क',
            'Login / Signup' => 'लगइन / साइनअप',
            'NepaCare' => 'नेपा-केयर',
            'Welcome Back' => 'फिरि स्वागत छ',
            'Please fill in all fields.' => 'कृपया सबै फिल्डहरू भर्नुहोस्।',
            'Enter a valid email or phone number starting with 97 or 98.' => 'कृपया 97 वा 98 बाट सुरु हुने मान्य इमेल वा फोन नम्बर प्रविष्ट गर्नुहोस्।',
            'Incorrect password.' => 'गलत पासवर्ड।',
            'User not found.' => 'प्रयोगकर्ता फेला परेन।',
            'Email or Phone' => 'इमेल वा फोन',
            'Password' => 'पासवर्ड',
            'Remember me' => 'मलाई सम्झनुहोस्',
            'Login' => 'लगइन',
            "Don't have an account?" => 'खाता छैन?',
            'Sign up' => 'साइन अप',
            'All rights reserved.' => 'सबै अधिकार सुरक्षित।',

            'Signup - NepaCare' => 'साइनअप - नेपा केयर',
            'Invalid phone number. Must start with 97 or 98 and be 10 digits.' => 'अमान्य फोन नम्बर। 97 वा 98 बाट सुरु हुनुपर्छ र 10 अंक हुनुपर्छ।',
            'Name can only contain letters and spaces.' => 'नाममा केवल अक्षर र स्पेस मात्र हुन सक्छ।',
            'Invalid email format.' => 'अमान्य इमेल ढाँचा।',
            'Email or phone already registered. Please login.' => 'इमेल वा फोन पहिले नै दर्ता छ। कृपया लगइन गर्नुहोस्।',
            "Signup successful! You can <a href='login.php'>login now</a>." => 'साइनअप सफल! अब तपाईंले लगइन गर्न सक्नुहुन्छ।',
            'Full Name' => 'पुरा नाम',
            'Phone (97 or 98...)' => 'फोन (97 वा 98...)',
            'Address' => 'ठेगाना',
            'Age' => 'उमेर',
            'Invalid age.' => 'अमान्य उमेर।',
            'Select Role' => 'भूमिका चयन गर्नुहोस्',
            'Elder' => 'जेष्ठ',
            'Caregiver' => 'हेरचाहकर्ता',
            'Already have an account?' => 'पहिलेबाट खाता छ?',
            'Login here' => 'यहाँ लगइन गर्नुहोस्'
            ,
            'Welcome to NepaCare' => 'नेपा केयरमा स्वागत छ',
            'For Elders' => 'जेष्ठहरूको लागि',
            'For Caregivers' => 'हेरचाहकर्ताहरूका लागि',
            'Manage your daily reminders, medicines, and tasks easily. Stay healthy and organized with NepaCare.' => 'तपाईंका दैनिक रिमाइन्डरहरू, औषधीहरू र कार्यहरू सजिलै व्यवस्थापन गर्नुहोस्। नेपा केयरसँग स्वस्थ र व्यवस्थित रहनुहोस्।',
            'Monitor elders’ reminders, support their health routines, and make caregiving easier.' => 'जेष्ठहरूको रिमाइन्डरहरू अनुगमन गर्नुहोस्, उनीहरूको स्वास्थ्य तालिका समर्थन गर्नुहोस्, र हेरचाह सजिलो बनाउनुहोस्।'
            ,
            'About paragraph' => 'नेपा केयर नेपालका जेष्ठ नागरिकहरुलाई दैनिक कार्य र औषधिहरु व्यवस्थापन गर्न सहयोग पुर्‍याउन समर्पित प्लेटफर्म हो जसले सुरक्षा र स्वास्थ्य सुनिश्चित गर्दछ। हेरचाहकर्ताहरुले पनि रिमाइन्डरहरु अनुगमन गर्न र जेष्ठहरुको समर्थन गर्न सक्नेछन्। हाम्रो लक्ष्य परिवार र पेशेवरहरूका लागि जेष्ठ हेरचाहलाई सरल बनाउनु हो।',
            'Feedback' => 'प्रतिक्रिया',
            'Submit Feedback' => 'प्रतिक्रिया पठाउनुहोस्',
            'Your feedback has been submitted.' => 'तपाईंको प्रतिक्रिया सफलतापूर्वक पठाइयो।',
            'Subject' => 'विषय',
            'Message' => 'सन्देश',
            'Send Feedback' => 'प्रतिक्रिया पठाउनुहोस्',
            'Please enter a message.' => 'कृपया सन्देश लेख्नुहोस्।',
            'Caregiver Dashboard' => 'हेरचाहकर्ता ड्यासबोर्ड',
            'Elders Under Your Care' => 'तपाईंको हेरचाहमा रहेका जेष्ठहरू',
            'Add New Elder' => 'नयाँ जेष्ठ थप्नुहोस्',
            'View Reminders' => 'रिमाइन्डरहरू हेर्नुहोस्',
            'No elders found.' => 'कुनै जेष्ठ फेला परेन।',
            'Elder Dashboard' => 'जेष्ठ ड्यासबोर्ड',
            'Your Reminders' => 'तपाईंका रिमाइन्डरहरू',
            'Add New Reminder' => 'नयाँ रिमाइन्डर थप्नुहोस्',
            'Mark as Done' => 'पूर्ण भएको रूपमा चिह्नित गर्नुहोस्',
            'No reminders found.' => 'कुनै रिमाइन्डर फेला परेन।',
            'Update Profile' => 'प्रोफाइल अपडेट गर्नुहोस्',
            'Profile updated successfully!' => 'प्रोफाइल सफलतापूर्वक अपडेट भयो!',
            'Add Reminder' => 'रिमाइन्डर थप्नुहोस्',
            'Get in Touch' => 'सम्पर्कमा आउनुहोस्',
            'Send Message' => 'सन्देश पठाउनुहोस्',
            'Thank you for your message!' => 'तपाईंको सन्देशका लागि धन्यवाद!',
            'Manage Users' => 'प्रयोगकर्ताहरू व्यवस्थापन गर्नुहोस्',
            'User List' => 'प्रयोगकर्ता सूची',
            'Approve' => 'अनुमोदन गर्नुहोस्',
            'Reject' => 'अस्वीकार गर्नुहोस्',
            'No users found.' => 'कुनै प्रयोगकर्ता फेला परेन।',
            'Manage Registrations' => 'दर्ताहरू व्यवस्थापन गर्नुहोस्',
            'Registration List' => 'दर्ता सूची',
            'No registrations found.' => 'कुनै दर्ता फेला परेन।',
            'Admin Dashboard' => 'एडमिन ड्यासबोर्ड',
            'Welcome to Admin Panel' => 'एडमिन प्यानलमा स्वागत छ',
            'Caregiver Profile' => 'हेरचाहकर्ता प्रोफाइल',
            'Caregiver Reminders' => 'हेरचाहकर्ता रिमाइन्डरहरू',
            'Reminders for Elder' => 'जेष्ठका लागि रिमाइन्डरहरू',
            'Elder Linked' => 'जेष्ठ लिङ्क गरिएको',
            'You are linked to Caregiver' => 'तपाईं हेरचाहकर्तासँग लिङ्क हुनुहुन्छ',
            'Caregiver Name' => 'हेरचाहकर्ताको नाम',
            'Caregiver Phone' => 'हेरचाहकर्ताको फोन',
            'Caregiver Email' => 'हेरचाहकर्ताको इमेल',
            'Generate OTP' => 'ओटीपी उत्पन्न गर्नुहोस्',
            'Enter your phone number' => 'तपाईंको फोन नम्बर प्रविष्ट गर्नुहोस्',
            'OTP sent successfully!' => 'ओटीपी सफलतापूर्वक पठाइयो!',
            'Are you sure?' => 'के तपाईं निश्चित हुनुहुन्छ?',
            'Welcome, ' => 'स्वागत छ, ',
            'Linked Elder: ' => 'लिङ्क गरिएको जेष्ठ: ',
            'No login records found.' => 'कुनै लगइन रेकर्ड फेला परेन।',
            'Caregiver about paragraph' => 'नेपा केयर नेपालका जेष्ठहरूका लागि विशेष रूपमा डिजाइन गरिएको सरल रिमाइन्डर र हेरचाह समर्थन प्रणाली हो। हेरचाहकर्ताको रूपमा, तपाईं जेष्ठहरूको रिमाइन्डरहरू व्यवस्थापन गरेर, तालिका जाँच गरेर र दैनिक कार्यहरू समर्थन गरेर मद्दत गर्न सक्नुहुन्छ।',
            'Reminders' => 'रिमाइन्डरहरू',
            'Link Elder' => 'जेष्ठ लिङ्क गर्नुहोस्',
            'Logout' => 'लगआउट',
            'Good morning' => 'शुभ प्रभात',
            'Good afternoon' => 'शुभ अपराह्न',
            'Good evening' => 'शुभ सन्ध्या',
            'Daily Activity Reminder' => 'दैनिक गतिविधि रिमाइन्डर',
            'Morning Walk' => 'बिहानको हिँडाइ',
            'Drink Water' => 'पानी पिउनुहोस्',
            'Exercise Time' => 'व्यायाम समय',
            'Health Tip' => 'स्वास्थ्य सुझाव',
            'Wellness Check' => 'कल्याण जाँच',
            'How are you feeling today?' => 'आज तपाईंलाई कस्तो लागिरहेको छ?',
            'Good' => 'राम्रो',
            'Okay' => 'ठीक',
            'Not well' => 'राम्रो छैन',
            'Elder about paragraph' => 'नेपा केयर जेष्ठहरूका लागि विशेष रूपमा डिजाइन गरिएको सरल, प्रयोग गर्न सजिलो रिमाइन्डर प्रणाली हो। तपाईं आफ्ना दैनिक कार्यहरू व्यवस्थापन गर्न सक्नुहुन्छ, रिमाइन्डरहरू सेट गर्न सक्नुहुन्छ, र जब केही महत्वपूर्ण गर्न समय हुन्छ तब अलर्टहरू प्राप्त गर्न सक्नुहुन्छ। यो प्रणाली सुनिश्चित गर्दछ कि तपाईंले कहिल्यै पनि कार्य छुटाउनुहुन्न र हेरचाहकर्ताहरूलाई सूचित राख्छ।',
            'Keep up the great work! Stay active today.' => 'राम्रो काम जारी राख्नुहोस्! आज सक्रिय रहनुहोस्।',
            'Take some rest and do light activity if possible.' => 'केही आराम लिनुहोस् र यदि सम्भव भएमा हल्का गतिविधि गर्नुहोस्।',
            'Please consult your caregiver or doctor if needed.' => 'आवश्यक भएमा आफ्नो हेरचाहकर्ता वा डाक्टरसँग परामर्श गर्नुहोस्।',
            'Contact NepaCare' => 'नेपा केयरलाई सम्पर्क गर्नुहोस्',
            'Contact paragraph' => 'कुनै पनि जिज्ञासा, प्रतिक्रिया वा समर्थनका लागि, कृपया हामीलाई सम्पर्क गर्नुहोस्: <br><br> <strong>इमेल:</strong> nepacare2082@gmail.com <br> <strong>फोन:</strong> +977-9841077161 <br> <strong>ठेगाना:</strong> काठमाडौं, नेपाल',
            'Help Tip 1' => 'सुझाव: स्वस्थ रहनका लागि समयमा औषधि लिन सम्झनुहोस्।',
            'Help Tip 2' => 'सुझाव: कहिल्यै नबिर्सनका लागि महत्वपूर्ण कार्यहरूका लागि रिमाइन्डरहरू सेट गर्नुहोस्।',
            'Help Tip 3' => 'सुझाव: राम्रो समर्थनका लागि आफ्ना दैनिक गतिविधिहरू आफ्नो हेरचाहकर्तासँग साझा गर्नुहोस्।',
            'Assigned Elders' => 'तोकिएका जेष्ठहरू',
            'Tasks' => 'कार्यहरू',
            'Linked Caregiver' => 'लिङ्क गरिएको हेरचाहकर्ता',
            'Health Tip 1' => 'सुझाव: हाइड्रेटेड रहनका लागि दैनिक प्रशस्त पानी पिउनुहोस्।',
            'Health Tip 2' => 'सुझाव: फलफूल र तरकारीहरू सहित सन्तुलित आहार खानुहोस्।',
            'Health Tip 3' => 'सुझाव: हरेक रात कम्तीमा ७-८ घण्टा निद्रा लिनुहोस्।',
            'Health Tip 4' => 'सुझाव: रक्तसञ्चार र मनोदशा सुधार गर्न छोटा हिँडाइहरू गर्नुहोस्।',
            'Profile' => 'प्रोफाइल',
            'Name' => 'नाम',
            'Email' => 'इमेल',
            'Phone' => 'फोन',
            'Address' => 'ठेगाना',
            'Age' => 'उमेर',
            'Change Password (leave blank to keep current)' => 'पासवर्ड परिवर्तन गर्नुहोस् (हालको राख्न खाली छोड्नुहोस्)',
            'Role:' => 'भूमिका:',
            'Current Time:' => 'हालको समय:',
            'Failed to update profile.' => 'प्रोफाइल अपडेट गर्न असफल भयो।',
            'Email or phone already in use by another user.' => 'इमेल वा फोन अर्को प्रयोगकर्ताद्वारा प्रयोगमा छ।',
            'Name, email, and phone cannot be empty.' => 'नाम, इमेल र फोन खाली हुन सक्दैन।'

        ],
        
    ];
}

if (!function_exists('get_current_lang')) {
    function get_current_lang(): string {
        if (!empty($_COOKIE['lang'])) {
            $l = preg_replace('/[^a-z]/', '', strtolower($_COOKIE['lang']));
            if (in_array($l, ['en','ne'])) return $l;
        }
        return 'en';
    }
}

if (!function_exists('__')) {
    function __(string $key): string {
        global $NEPA_LANGS;
        $lang = get_current_lang();
        if (isset($NEPA_LANGS[$lang]) && array_key_exists($key, $NEPA_LANGS[$lang])) {
            return $NEPA_LANGS[$lang][$key];
        }
        if (isset($NEPA_LANGS['en'][$key])) return $NEPA_LANGS['en'][$key];
        return $key;
    }
}

$AVAILABLE_LANGS = ['en' => 'English', 'ne' => 'नेपाली'];

?>
